---
include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  ADDON_GITHUB_REPO: "hassio-addons/addon-sqlite-web"
  ADDON_SLUG: "sqlite-web"
  ADDON_TARGET: "sqlite-web"


  ADDON_AARCH64_BASE: "hassioaddons/base-python-aarch64:1.1.0"
  ADDON_AMD64_BASE: "hassioaddons/base-python-amd64:1.1.0"
  ADDON_ARMHF_BASE: "hassioaddons/base-python-armhf:1.1.0"
  ADDON_ARMV7_BASE: "hassioaddons/base-python-armv7:1.1.0"
  ADDON_I386_BASE: "hassioaddons/base-python-i386:1.1.0"
